version: "3"
networks:
  main:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/logs:/etc/logs/nginx
      - ./app:/web/backend
      - ./frontend:/web/frontend
      - ./nginx/conf:/etc/nginx/conf.d
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: nginx -g "daemon off;"
    networks:
      main:
        aliases:
            - nginx

  php:
    image: fraqtop/fpm-postgres
    volumes:
      - ./app:/web/backend
    user: 1000:1000
    networks:
      main:
        aliases:
            - php

  composer:
    image: composer
    working_dir: /web/backend
    volumes:
      - ./app:/web/backend
    command: composer update

  database:
    image: postgres:latest
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - database

  redis-server:
    image: redis:latest
    networks:
      main:
        aliases:
          - redis-server

  front:
    image: node:lts-alpine
    user: 'node'
    working_dir: /web/frontend
    volumes:
      - ./frontend:/web/frontend
    command: sh -c "npm i && npm run build && npm run dev"
    ports:
      - 8080:8080
    networks:
      main:
        aliases:
          - front