version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./nginx/logs:/etc/logs/nginx
      - ./app:/var/www/html
      - ./nginx/conf:/etc/nginx/conf.d
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    links:
      - php
    command: nginx -g "daemon off;"

  php:
    image: fraqtop/fpm-postgres
    volumes:
      - ./app:/var/www/html
    links:
      - database
      - redis-server
    user: 1000:1000

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data

  redis-server:
    image: redis:latest


  adminer:
    image: adminer
    ports:
      - 8080:8080